name: SAM Deploy Pipeline

on:
  workflow_call:
    inputs:
      sam_template:
        required: true 
        type: string
      stack_name:
        required: true
        type: string
      pipeline_execution_role_arn:
        required: true
        type: string
      cloudformation_execution_role_arn:
        required: true
        type: string
      artifacts_s3_bucket_name:
        required: true
        type: string
      region:
        required: true
        type: string
      sam_config_filename:
        required: true
        type: string
      sam_config_environment_name:
        required: true
        type: string
    secrets:
      PIPELINE_USER_ACCESS_KEY_ID:
        required: true
      PIPELINE_USER_SECRET_ACCESS_KEY:
        required: true

env:
  SAM_CLI_TELEMETRY: 0
  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.PIPELINE_USER_ACCESS_KEY_ID }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.PIPELINE_USER_SECRET_ACCESS_KEY }}
  SAM_TEMPLATE: ${{ inputs.sam_template }}
  STACK_NAME: ${{ inputs.stack_name }}
  PIPELINE_EXECUTION_ROLE: ${{ inputs.pipeline_execution_role_arn }}
  CLOUDFORMATION_EXECUTION_ROLE: ${{ inputs.cloudformation_execution_role_arn }}
  ARTIFACTS_BUCKET: ${{ inputs.artifacts_s3_bucket_name }}
  REGION: ${{ inputs.region }}
  SAM_CONFIG_FILENAME: ${{ inputs.sam_config_filename }}
  SAM_CONFIG_ENVIRONMENT_NAME: ${{ inputs.sam_config_environment_name }}
  SAM_PACKAGED_TEMPLATE: 'packaged-template.yaml'

jobs:
  deploy-sam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1

      - name: Build resources
        shell: bash
        run: |
          sam build \
            --use-container \
            --template ${SAM_TEMPLATE} \
            --config-file ${SAM_CONFIG_FILENAME} \
            --config-env ${SAM_CONFIG_ENVIRONMENT_NAME}

      - name: Assume the pipeline role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
          role-session-name: github-action-deploy-sam
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Upload artifacts to S3 bucket
        shell: bash
        run: |
          sam package \
            --config-file ${SAM_CONFIG_FILENAME} \
            --config-env ${SAM_CONFIG_ENVIRONMENT_NAME} \
            --region ${REGION} \
            --s3-bucket ${ARTIFACTS_BUCKET} \
            --s3-prefix "${SAM_CONFIG_ENVIRONMENT_NAME}/${STACK_NAME}" \
            --output-template-file "${SAM_PACKAGED_TEMPLATE}"

      - name: Deploy to account
        shell: bash
        run: |
          sam deploy \
            --no-fail-on-empty-changeset \
            --stack-name ${STACK_NAME} \
            --config-file ${SAM_CONFIG_FILENAME} \
            --config-env ${SAM_CONFIG_ENVIRONMENT_NAME} \
            --region ${REGION} \
            --s3-bucket ${ARTIFACTS_BUCKET} \
            --s3-prefix "${SAM_CONFIG_ENVIRONMENT_NAME}/${STACK_NAME}" \
            --role-arn ${CLOUDFORMATION_EXECUTION_ROLE} \
            --template "${SAM_PACKAGED_TEMPLATE}"

