name: SAM Deploy Pipeline

on:
  workflow_call:
    inputs:
      sam_template:
        required: true 
        type: string
      stack_name:
        required: true
        type: string
      pipeline_execution_role_arn:
        required: true
        type: string
      cloudformation_execution_role_arn:
        required: true
        type: string
      artifacts_s3_bucket_name:
        required: true
        type: string
      region:
        required: true
        type: string
      sam_config_filename:
        required: true
        type: string
      sam_config_environment_name:
        required: true
        type: string
      replacement_variable_list:
        description: 'A comma separeted list of replacemente variables to iterate to be applied on sam_config_filename'
        required: false
        type: string
      replacement_value_list:
        description: 'A comma separeted list of replacemente values to iterate to be applied on sam_config_filename'
        required: false
        type: string
    secrets:
      PIPELINE_USER_ACCESS_KEY_ID:
        required: true
      PIPELINE_USER_SECRET_ACCESS_KEY:
        required: true

env:
  SAM_CLI_TELEMETRY: 0
  SAM_PACKAGED_TEMPLATE: 'packaged-template.yaml'

jobs:
  deploy-sam:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v3
      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with: 
          use-installer: true
      - name: Applying Replacements
        shell: bash
        run: |
          OLD_IFS=$IFS
          IFS=';'
          variables=${{ inputs.replacement_variable_list }}
          values=${{ inputs.replacement_value_list }}
          if [[ -z "${variables}" ]]
          then
            echo "There are no replacements to be evaluated."
          elif [[ ${!variables[*]} == 0 ]]
          then
            echo "There are 1 replacement to be evaluated."
            echo "Replacing %${variables}% by '${values}'"
            sed -i -e "s/%${variables}%/${values}/g" ${{ inputs.sam_config_filename }}
          else
            echo "There are ${!variables[*]} replacements to be evaluated."
            for pos in ${!variables[*]}
            do
              echo "Replacing %variables[$pos]% by 'values[$pos]'"
              sed -i -e "s/%variables[$pos]%/values[$pos]/g" ${{ inputs.sam_config_filename }}
            done
          fi
          IFS=$OLD_IFS
      - name: Build resources
        shell: bash
        run: |
          sam build \
            --use-container \
            --template ${{ inputs.sam_template }} \
            --config-file ${{ inputs.sam_config_filename }} \
            --config-env ${{ inputs.sam_config_environment_name }}

      - name: Assume the pipeline role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
          role-to-assume: ${{ inputs.pipeline_execution_role_arn }}
          role-session-name: github-action-deploy-sam
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Upload artifacts to S3 bucket
        shell: bash
        run: |
          sam package \
            --config-file ${{ inputs.sam_config_filename }} \
            --config-env ${{ inputs.sam_config_environment_name }} \
            --region ${{ inputs.region }} \
            --s3-bucket ${{ inputs.artifacts_s3_bucket_name }} \
            --s3-prefix "${{ inputs.sam_config_environment_name }}/${{ inputs.stack_name }}" \
            --output-template-file "${SAM_PACKAGED_TEMPLATE}"

      - name: Deploy to account
        shell: bash
        run: |
          sam deploy \
            --no-fail-on-empty-changeset \
            --stack-name ${{ inputs.stack_name }} \
            --config-file ${{ inputs.sam_config_filename }} \
            --config-env ${{ inputs.sam_config_environment_name }} \
            --region ${{ inputs.region }} \
            --s3-bucket ${{ inputs.artifacts_s3_bucket_name }} \
            --s3-prefix "${{ inputs.sam_config_environment_name }}/${{ inputs.stack_name }}" \
            --role-arn ${{ inputs.cloudformation_execution_role_arn }} \
            --template "${SAM_PACKAGED_TEMPLATE}"

