name: SAM Undeploy Pipeline

on:
  workflow_call:
    inputs:
      stack_name:
        required: true
        type: string
      pipeline_execution_role_arn:
        required: true
        type: string
      artifacts_s3_bucket_name:
        required: true
        type: string
      region:
        required: true
        type: string
      sam_config_filename:
        required: true
        type: string
      sam_config_environment_name:
        required: true
        type: string
    secrets:
      PIPELINE_USER_ACCESS_KEY_ID:
        required: true
      PIPELINE_USER_SECRET_ACCESS_KEY:
        required: true

env:
  SAM_CLI_TELEMETRY: 0

jobs:
  undeploy-sam:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v3
      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with: 
          use-installer: true

      - name: Assume the pipeline user role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
          role-to-assume: ${{ inputs.pipeline_execution_role_arn }}
          role-session-name: github-action-undeploy-sam
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Delete stack
        run: |
          sam delete \
            --no-prompts \
            --stack-name ${{ inputs.stack_name }} \
            --config-file ${{ inputs.sam_config_filename }} \
            --config-env ${{ inputs.sam_config_environment_name }} \
            --region ${{ inputs.region }} \
            --s3-bucket ${{ inputs.artifacts_s3_bucket_name }} \
            --s3-prefix "${{ inputs.sam_config_environment_name }}/${{ inputs.stack_name }}"
